#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QuanLyks")]
	public partial class HotelDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertchitietdatphong(chitietdatphong instance);
    partial void Updatechitietdatphong(chitietdatphong instance);
    partial void Deletechitietdatphong(chitietdatphong instance);
    partial void Insertchitietthuephong(chitietthuephong instance);
    partial void Updatechitietthuephong(chitietthuephong instance);
    partial void Deletechitietthuephong(chitietthuephong instance);
    partial void Insertchitietvattu(chitietvattu instance);
    partial void Updatechitietvattu(chitietvattu instance);
    partial void Deletechitietvattu(chitietvattu instance);
    partial void Insertdichvu(dichvu instance);
    partial void Updatedichvu(dichvu instance);
    partial void Deletedichvu(dichvu instance);
    partial void Inserthethong(hethong instance);
    partial void Updatehethong(hethong instance);
    partial void Deletehethong(hethong instance);
    partial void Inserthoadon(hoadon instance);
    partial void Updatehoadon(hoadon instance);
    partial void Deletehoadon(hoadon instance);
    partial void Insertkhachhang(khachhang instance);
    partial void Updatekhachhang(khachhang instance);
    partial void Deletekhachhang(khachhang instance);
    partial void Insertphong(phong instance);
    partial void Updatephong(phong instance);
    partial void Deletephong(phong instance);
    partial void Insertloaiphong(loaiphong instance);
    partial void Updateloaiphong(loaiphong instance);
    partial void Deleteloaiphong(loaiphong instance);
    partial void Insertnhanvien(nhanvien instance);
    partial void Updatenhanvien(nhanvien instance);
    partial void Deletenhanvien(nhanvien instance);
    partial void Insertphieudatphong(phieudatphong instance);
    partial void Updatephieudatphong(phieudatphong instance);
    partial void Deletephieudatphong(phieudatphong instance);
    partial void Insertphieuthuephong(phieuthuephong instance);
    partial void Updatephieuthuephong(phieuthuephong instance);
    partial void Deletephieuthuephong(phieuthuephong instance);
    partial void Inserttrangthaiphong(trangthaiphong instance);
    partial void Updatetrangthaiphong(trangthaiphong instance);
    partial void Deletetrangthaiphong(trangthaiphong instance);
    partial void Insertvattu(vattu instance);
    partial void Updatevattu(vattu instance);
    partial void Deletevattu(vattu instance);
    #endregion
		
		public HotelDataContext() : 
				base(global::DAO.Properties.Settings.Default.QuanLyksConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public HotelDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HotelDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HotelDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HotelDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<chitietdatphong> chitietdatphongs
		{
			get
			{
				return this.GetTable<chitietdatphong>();
			}
		}
		
		public System.Data.Linq.Table<chitietthuephong> chitietthuephongs
		{
			get
			{
				return this.GetTable<chitietthuephong>();
			}
		}
		
		public System.Data.Linq.Table<chitietvattu> chitietvattus
		{
			get
			{
				return this.GetTable<chitietvattu>();
			}
		}
		
		public System.Data.Linq.Table<dichvu> dichvus
		{
			get
			{
				return this.GetTable<dichvu>();
			}
		}
		
		public System.Data.Linq.Table<hethong> hethongs
		{
			get
			{
				return this.GetTable<hethong>();
			}
		}
		
		public System.Data.Linq.Table<hoadon> hoadons
		{
			get
			{
				return this.GetTable<hoadon>();
			}
		}
		
		public System.Data.Linq.Table<khachhang> khachhangs
		{
			get
			{
				return this.GetTable<khachhang>();
			}
		}
		
		public System.Data.Linq.Table<phong> phongs
		{
			get
			{
				return this.GetTable<phong>();
			}
		}
		
		public System.Data.Linq.Table<loaiphong> loaiphongs
		{
			get
			{
				return this.GetTable<loaiphong>();
			}
		}
		
		public System.Data.Linq.Table<nhanvien> nhanviens
		{
			get
			{
				return this.GetTable<nhanvien>();
			}
		}
		
		public System.Data.Linq.Table<phieudatphong> phieudatphongs
		{
			get
			{
				return this.GetTable<phieudatphong>();
			}
		}
		
		public System.Data.Linq.Table<phieuthuephong> phieuthuephongs
		{
			get
			{
				return this.GetTable<phieuthuephong>();
			}
		}
		
		public System.Data.Linq.Table<trangthaiphong> trangthaiphongs
		{
			get
			{
				return this.GetTable<trangthaiphong>();
			}
		}
		
		public System.Data.Linq.Table<vattu> vattus
		{
			get
			{
				return this.GetTable<vattu>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.InhoadonDichVu")]
		public ISingleResult<InhoadonDichVuResult> InhoadonDichVu([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string mahoadon)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mahoadon);
			return ((ISingleResult<InhoadonDichVuResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.InhoadonPhong")]
		public ISingleResult<InhoadonPhongResult> InhoadonPhong([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string mahoadon)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mahoadon);
			return ((ISingleResult<InhoadonPhongResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.kiemtraphong")]
		public ISingleResult<kiemtraphongResult> kiemtraphong([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> ngayden, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> ngaydi)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), ngayden, ngaydi);
			return ((ISingleResult<kiemtraphongResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.chitietdatphong")]
	public partial class chitietdatphong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maphieudat;
		
		private string _maphong;
		
		private EntityRef<phong> _phong;
		
		private EntityRef<phieudatphong> _phieudatphong;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaphieudatChanging(string value);
    partial void OnmaphieudatChanged();
    partial void OnmaphongChanging(string value);
    partial void OnmaphongChanged();
    #endregion
		
		public chitietdatphong()
		{
			this._phong = default(EntityRef<phong>);
			this._phieudatphong = default(EntityRef<phieudatphong>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maphieudat", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maphieudat
		{
			get
			{
				return this._maphieudat;
			}
			set
			{
				if ((this._maphieudat != value))
				{
					if (this._phieudatphong.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaphieudatChanging(value);
					this.SendPropertyChanging();
					this._maphieudat = value;
					this.SendPropertyChanged("maphieudat");
					this.OnmaphieudatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maphong", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maphong
		{
			get
			{
				return this._maphong;
			}
			set
			{
				if ((this._maphong != value))
				{
					if (this._phong.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaphongChanging(value);
					this.SendPropertyChanging();
					this._maphong = value;
					this.SendPropertyChanged("maphong");
					this.OnmaphongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="phong_chitietdatphong", Storage="_phong", ThisKey="maphong", OtherKey="maphong", IsForeignKey=true)]
		public phong phong
		{
			get
			{
				return this._phong.Entity;
			}
			set
			{
				phong previousValue = this._phong.Entity;
				if (((previousValue != value) 
							|| (this._phong.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._phong.Entity = null;
						previousValue.chitietdatphongs.Remove(this);
					}
					this._phong.Entity = value;
					if ((value != null))
					{
						value.chitietdatphongs.Add(this);
						this._maphong = value.maphong;
					}
					else
					{
						this._maphong = default(string);
					}
					this.SendPropertyChanged("phong");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="phieudatphong_chitietdatphong", Storage="_phieudatphong", ThisKey="maphieudat", OtherKey="maphieudat", IsForeignKey=true)]
		public phieudatphong phieudatphong
		{
			get
			{
				return this._phieudatphong.Entity;
			}
			set
			{
				phieudatphong previousValue = this._phieudatphong.Entity;
				if (((previousValue != value) 
							|| (this._phieudatphong.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._phieudatphong.Entity = null;
						previousValue.chitietdatphongs.Remove(this);
					}
					this._phieudatphong.Entity = value;
					if ((value != null))
					{
						value.chitietdatphongs.Add(this);
						this._maphieudat = value.maphieudat;
					}
					else
					{
						this._maphieudat = default(string);
					}
					this.SendPropertyChanged("phieudatphong");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.chitietthuephong")]
	public partial class chitietthuephong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maphieuthue;
		
		private string _maphong;
		
		private System.DateTime _ngay;
		
		private string _madichvu;
		
		private System.Nullable<int> _soluong;
		
		private EntityRef<dichvu> _dichvu;
		
		private EntityRef<phong> _phong;
		
		private EntityRef<phieuthuephong> _phieuthuephong;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaphieuthueChanging(string value);
    partial void OnmaphieuthueChanged();
    partial void OnmaphongChanging(string value);
    partial void OnmaphongChanged();
    partial void OnngayChanging(System.DateTime value);
    partial void OnngayChanged();
    partial void OnmadichvuChanging(string value);
    partial void OnmadichvuChanged();
    partial void OnsoluongChanging(System.Nullable<int> value);
    partial void OnsoluongChanged();
    #endregion
		
		public chitietthuephong()
		{
			this._dichvu = default(EntityRef<dichvu>);
			this._phong = default(EntityRef<phong>);
			this._phieuthuephong = default(EntityRef<phieuthuephong>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maphieuthue", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maphieuthue
		{
			get
			{
				return this._maphieuthue;
			}
			set
			{
				if ((this._maphieuthue != value))
				{
					if (this._phieuthuephong.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaphieuthueChanging(value);
					this.SendPropertyChanging();
					this._maphieuthue = value;
					this.SendPropertyChanged("maphieuthue");
					this.OnmaphieuthueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maphong", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maphong
		{
			get
			{
				return this._maphong;
			}
			set
			{
				if ((this._maphong != value))
				{
					if (this._phong.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaphongChanging(value);
					this.SendPropertyChanging();
					this._maphong = value;
					this.SendPropertyChanged("maphong");
					this.OnmaphongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay", DbType="DateTime NOT NULL", IsPrimaryKey=true)]
		public System.DateTime ngay
		{
			get
			{
				return this._ngay;
			}
			set
			{
				if ((this._ngay != value))
				{
					this.OnngayChanging(value);
					this.SendPropertyChanging();
					this._ngay = value;
					this.SendPropertyChanged("ngay");
					this.OnngayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_madichvu", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string madichvu
		{
			get
			{
				return this._madichvu;
			}
			set
			{
				if ((this._madichvu != value))
				{
					if (this._dichvu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmadichvuChanging(value);
					this.SendPropertyChanging();
					this._madichvu = value;
					this.SendPropertyChanged("madichvu");
					this.OnmadichvuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soluong", DbType="Int")]
		public System.Nullable<int> soluong
		{
			get
			{
				return this._soluong;
			}
			set
			{
				if ((this._soluong != value))
				{
					this.OnsoluongChanging(value);
					this.SendPropertyChanging();
					this._soluong = value;
					this.SendPropertyChanged("soluong");
					this.OnsoluongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="dichvu_chitietthuephong", Storage="_dichvu", ThisKey="madichvu", OtherKey="madichvu", IsForeignKey=true)]
		public dichvu dichvu
		{
			get
			{
				return this._dichvu.Entity;
			}
			set
			{
				dichvu previousValue = this._dichvu.Entity;
				if (((previousValue != value) 
							|| (this._dichvu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._dichvu.Entity = null;
						previousValue.chitietthuephongs.Remove(this);
					}
					this._dichvu.Entity = value;
					if ((value != null))
					{
						value.chitietthuephongs.Add(this);
						this._madichvu = value.madichvu;
					}
					else
					{
						this._madichvu = default(string);
					}
					this.SendPropertyChanged("dichvu");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="phong_chitietthuephong", Storage="_phong", ThisKey="maphong", OtherKey="maphong", IsForeignKey=true)]
		public phong phong
		{
			get
			{
				return this._phong.Entity;
			}
			set
			{
				phong previousValue = this._phong.Entity;
				if (((previousValue != value) 
							|| (this._phong.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._phong.Entity = null;
						previousValue.chitietthuephongs.Remove(this);
					}
					this._phong.Entity = value;
					if ((value != null))
					{
						value.chitietthuephongs.Add(this);
						this._maphong = value.maphong;
					}
					else
					{
						this._maphong = default(string);
					}
					this.SendPropertyChanged("phong");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="phieuthuephong_chitietthuephong", Storage="_phieuthuephong", ThisKey="maphieuthue", OtherKey="maphieuthue", IsForeignKey=true)]
		public phieuthuephong phieuthuephong
		{
			get
			{
				return this._phieuthuephong.Entity;
			}
			set
			{
				phieuthuephong previousValue = this._phieuthuephong.Entity;
				if (((previousValue != value) 
							|| (this._phieuthuephong.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._phieuthuephong.Entity = null;
						previousValue.chitietthuephongs.Remove(this);
					}
					this._phieuthuephong.Entity = value;
					if ((value != null))
					{
						value.chitietthuephongs.Add(this);
						this._maphieuthue = value.maphieuthue;
					}
					else
					{
						this._maphieuthue = default(string);
					}
					this.SendPropertyChanged("phieuthuephong");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.chitietvattu")]
	public partial class chitietvattu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _mavattu;
		
		private string _maloaiphong;
		
		private System.Nullable<int> _soluong;
		
		private EntityRef<loaiphong> _loaiphong;
		
		private EntityRef<vattu> _vattu;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmavattuChanging(string value);
    partial void OnmavattuChanged();
    partial void OnmaloaiphongChanging(string value);
    partial void OnmaloaiphongChanged();
    partial void OnsoluongChanging(System.Nullable<int> value);
    partial void OnsoluongChanged();
    #endregion
		
		public chitietvattu()
		{
			this._loaiphong = default(EntityRef<loaiphong>);
			this._vattu = default(EntityRef<vattu>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mavattu", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string mavattu
		{
			get
			{
				return this._mavattu;
			}
			set
			{
				if ((this._mavattu != value))
				{
					if (this._vattu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmavattuChanging(value);
					this.SendPropertyChanging();
					this._mavattu = value;
					this.SendPropertyChanged("mavattu");
					this.OnmavattuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maloaiphong", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maloaiphong
		{
			get
			{
				return this._maloaiphong;
			}
			set
			{
				if ((this._maloaiphong != value))
				{
					if (this._loaiphong.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaloaiphongChanging(value);
					this.SendPropertyChanging();
					this._maloaiphong = value;
					this.SendPropertyChanged("maloaiphong");
					this.OnmaloaiphongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soluong", DbType="Int")]
		public System.Nullable<int> soluong
		{
			get
			{
				return this._soluong;
			}
			set
			{
				if ((this._soluong != value))
				{
					this.OnsoluongChanging(value);
					this.SendPropertyChanging();
					this._soluong = value;
					this.SendPropertyChanged("soluong");
					this.OnsoluongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="loaiphong_chitietvattu", Storage="_loaiphong", ThisKey="maloaiphong", OtherKey="maloai", IsForeignKey=true)]
		public loaiphong loaiphong
		{
			get
			{
				return this._loaiphong.Entity;
			}
			set
			{
				loaiphong previousValue = this._loaiphong.Entity;
				if (((previousValue != value) 
							|| (this._loaiphong.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._loaiphong.Entity = null;
						previousValue.chitietvattus.Remove(this);
					}
					this._loaiphong.Entity = value;
					if ((value != null))
					{
						value.chitietvattus.Add(this);
						this._maloaiphong = value.maloai;
					}
					else
					{
						this._maloaiphong = default(string);
					}
					this.SendPropertyChanged("loaiphong");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="vattu_chitietvattu", Storage="_vattu", ThisKey="mavattu", OtherKey="mavattu", IsForeignKey=true)]
		public vattu vattu
		{
			get
			{
				return this._vattu.Entity;
			}
			set
			{
				vattu previousValue = this._vattu.Entity;
				if (((previousValue != value) 
							|| (this._vattu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._vattu.Entity = null;
						previousValue.chitietvattus.Remove(this);
					}
					this._vattu.Entity = value;
					if ((value != null))
					{
						value.chitietvattus.Add(this);
						this._mavattu = value.mavattu;
					}
					else
					{
						this._mavattu = default(string);
					}
					this.SendPropertyChanged("vattu");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.dichvu")]
	public partial class dichvu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _madichvu;
		
		private string _tendichvu;
		
		private System.Nullable<decimal> _gia;
		
		private string _donvitinh;
		
		private EntitySet<chitietthuephong> _chitietthuephongs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmadichvuChanging(string value);
    partial void OnmadichvuChanged();
    partial void OntendichvuChanging(string value);
    partial void OntendichvuChanged();
    partial void OngiaChanging(System.Nullable<decimal> value);
    partial void OngiaChanged();
    partial void OndonvitinhChanging(string value);
    partial void OndonvitinhChanged();
    #endregion
		
		public dichvu()
		{
			this._chitietthuephongs = new EntitySet<chitietthuephong>(new Action<chitietthuephong>(this.attach_chitietthuephongs), new Action<chitietthuephong>(this.detach_chitietthuephongs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_madichvu", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string madichvu
		{
			get
			{
				return this._madichvu;
			}
			set
			{
				if ((this._madichvu != value))
				{
					this.OnmadichvuChanging(value);
					this.SendPropertyChanging();
					this._madichvu = value;
					this.SendPropertyChanged("madichvu");
					this.OnmadichvuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tendichvu", DbType="NVarChar(50)")]
		public string tendichvu
		{
			get
			{
				return this._tendichvu;
			}
			set
			{
				if ((this._tendichvu != value))
				{
					this.OntendichvuChanging(value);
					this.SendPropertyChanging();
					this._tendichvu = value;
					this.SendPropertyChanged("tendichvu");
					this.OntendichvuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gia", DbType="Money")]
		public System.Nullable<decimal> gia
		{
			get
			{
				return this._gia;
			}
			set
			{
				if ((this._gia != value))
				{
					this.OngiaChanging(value);
					this.SendPropertyChanging();
					this._gia = value;
					this.SendPropertyChanged("gia");
					this.OngiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_donvitinh", DbType="NChar(10)")]
		public string donvitinh
		{
			get
			{
				return this._donvitinh;
			}
			set
			{
				if ((this._donvitinh != value))
				{
					this.OndonvitinhChanging(value);
					this.SendPropertyChanging();
					this._donvitinh = value;
					this.SendPropertyChanged("donvitinh");
					this.OndonvitinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="dichvu_chitietthuephong", Storage="_chitietthuephongs", ThisKey="madichvu", OtherKey="madichvu")]
		public EntitySet<chitietthuephong> chitietthuephongs
		{
			get
			{
				return this._chitietthuephongs;
			}
			set
			{
				this._chitietthuephongs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_chitietthuephongs(chitietthuephong entity)
		{
			this.SendPropertyChanging();
			entity.dichvu = this;
		}
		
		private void detach_chitietthuephongs(chitietthuephong entity)
		{
			this.SendPropertyChanging();
			entity.dichvu = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.hethong")]
	public partial class hethong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _username;
		
		private string _manhanvien;
		
		private string _password;
		
		private EntitySet<hoadon> _hoadons;
		
		private EntitySet<phieuthuephong> _phieuthuephongs;
		
		private EntityRef<nhanvien> _nhanvien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OnmanhanvienChanging(string value);
    partial void OnmanhanvienChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    #endregion
		
		public hethong()
		{
			this._hoadons = new EntitySet<hoadon>(new Action<hoadon>(this.attach_hoadons), new Action<hoadon>(this.detach_hoadons));
			this._phieuthuephongs = new EntitySet<phieuthuephong>(new Action<phieuthuephong>(this.attach_phieuthuephongs), new Action<phieuthuephong>(this.detach_phieuthuephongs));
			this._nhanvien = default(EntityRef<nhanvien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_manhanvien", DbType="VarChar(10)")]
		public string manhanvien
		{
			get
			{
				return this._manhanvien;
			}
			set
			{
				if ((this._manhanvien != value))
				{
					if (this._nhanvien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmanhanvienChanging(value);
					this.SendPropertyChanging();
					this._manhanvien = value;
					this.SendPropertyChanged("manhanvien");
					this.OnmanhanvienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="VarChar(200)")]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="hethong_hoadon", Storage="_hoadons", ThisKey="username", OtherKey="username")]
		public EntitySet<hoadon> hoadons
		{
			get
			{
				return this._hoadons;
			}
			set
			{
				this._hoadons.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="hethong_phieuthuephong", Storage="_phieuthuephongs", ThisKey="username", OtherKey="username")]
		public EntitySet<phieuthuephong> phieuthuephongs
		{
			get
			{
				return this._phieuthuephongs;
			}
			set
			{
				this._phieuthuephongs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nhanvien_hethong", Storage="_nhanvien", ThisKey="manhanvien", OtherKey="manhanvien", IsForeignKey=true)]
		public nhanvien nhanvien
		{
			get
			{
				return this._nhanvien.Entity;
			}
			set
			{
				nhanvien previousValue = this._nhanvien.Entity;
				if (((previousValue != value) 
							|| (this._nhanvien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._nhanvien.Entity = null;
						previousValue.hethongs.Remove(this);
					}
					this._nhanvien.Entity = value;
					if ((value != null))
					{
						value.hethongs.Add(this);
						this._manhanvien = value.manhanvien;
					}
					else
					{
						this._manhanvien = default(string);
					}
					this.SendPropertyChanged("nhanvien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_hoadons(hoadon entity)
		{
			this.SendPropertyChanging();
			entity.hethong = this;
		}
		
		private void detach_hoadons(hoadon entity)
		{
			this.SendPropertyChanging();
			entity.hethong = null;
		}
		
		private void attach_phieuthuephongs(phieuthuephong entity)
		{
			this.SendPropertyChanging();
			entity.hethong = this;
		}
		
		private void detach_phieuthuephongs(phieuthuephong entity)
		{
			this.SendPropertyChanging();
			entity.hethong = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.hoadon")]
	public partial class hoadon : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _mahoadon;
		
		private System.DateTime _ngaythanhtoan;
		
		private System.Nullable<decimal> _tongtien;
		
		private string _maphieuthue;
		
		private string _makhachhang;
		
		private string _username;
		
		private EntityRef<hethong> _hethong;
		
		private EntityRef<khachhang> _khachhang;
		
		private EntityRef<phieuthuephong> _phieuthuephong;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmahoadonChanging(string value);
    partial void OnmahoadonChanged();
    partial void OnngaythanhtoanChanging(System.DateTime value);
    partial void OnngaythanhtoanChanged();
    partial void OntongtienChanging(System.Nullable<decimal> value);
    partial void OntongtienChanged();
    partial void OnmaphieuthueChanging(string value);
    partial void OnmaphieuthueChanged();
    partial void OnmakhachhangChanging(string value);
    partial void OnmakhachhangChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    #endregion
		
		public hoadon()
		{
			this._hethong = default(EntityRef<hethong>);
			this._khachhang = default(EntityRef<khachhang>);
			this._phieuthuephong = default(EntityRef<phieuthuephong>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mahoadon", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string mahoadon
		{
			get
			{
				return this._mahoadon;
			}
			set
			{
				if ((this._mahoadon != value))
				{
					this.OnmahoadonChanging(value);
					this.SendPropertyChanging();
					this._mahoadon = value;
					this.SendPropertyChanged("mahoadon");
					this.OnmahoadonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaythanhtoan", DbType="DateTime NOT NULL")]
		public System.DateTime ngaythanhtoan
		{
			get
			{
				return this._ngaythanhtoan;
			}
			set
			{
				if ((this._ngaythanhtoan != value))
				{
					this.OnngaythanhtoanChanging(value);
					this.SendPropertyChanging();
					this._ngaythanhtoan = value;
					this.SendPropertyChanged("ngaythanhtoan");
					this.OnngaythanhtoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tongtien", DbType="Money")]
		public System.Nullable<decimal> tongtien
		{
			get
			{
				return this._tongtien;
			}
			set
			{
				if ((this._tongtien != value))
				{
					this.OntongtienChanging(value);
					this.SendPropertyChanging();
					this._tongtien = value;
					this.SendPropertyChanged("tongtien");
					this.OntongtienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maphieuthue", DbType="VarChar(10)")]
		public string maphieuthue
		{
			get
			{
				return this._maphieuthue;
			}
			set
			{
				if ((this._maphieuthue != value))
				{
					if (this._phieuthuephong.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaphieuthueChanging(value);
					this.SendPropertyChanging();
					this._maphieuthue = value;
					this.SendPropertyChanged("maphieuthue");
					this.OnmaphieuthueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_makhachhang", DbType="VarChar(10)")]
		public string makhachhang
		{
			get
			{
				return this._makhachhang;
			}
			set
			{
				if ((this._makhachhang != value))
				{
					if (this._khachhang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmakhachhangChanging(value);
					this.SendPropertyChanging();
					this._makhachhang = value;
					this.SendPropertyChanged("makhachhang");
					this.OnmakhachhangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="VarChar(10)")]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					if (this._hethong.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="hethong_hoadon", Storage="_hethong", ThisKey="username", OtherKey="username", IsForeignKey=true)]
		public hethong hethong
		{
			get
			{
				return this._hethong.Entity;
			}
			set
			{
				hethong previousValue = this._hethong.Entity;
				if (((previousValue != value) 
							|| (this._hethong.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._hethong.Entity = null;
						previousValue.hoadons.Remove(this);
					}
					this._hethong.Entity = value;
					if ((value != null))
					{
						value.hoadons.Add(this);
						this._username = value.username;
					}
					else
					{
						this._username = default(string);
					}
					this.SendPropertyChanged("hethong");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="khachhang_hoadon", Storage="_khachhang", ThisKey="makhachhang", OtherKey="makhachhang", IsForeignKey=true)]
		public khachhang khachhang
		{
			get
			{
				return this._khachhang.Entity;
			}
			set
			{
				khachhang previousValue = this._khachhang.Entity;
				if (((previousValue != value) 
							|| (this._khachhang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._khachhang.Entity = null;
						previousValue.hoadons.Remove(this);
					}
					this._khachhang.Entity = value;
					if ((value != null))
					{
						value.hoadons.Add(this);
						this._makhachhang = value.makhachhang;
					}
					else
					{
						this._makhachhang = default(string);
					}
					this.SendPropertyChanged("khachhang");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="phieuthuephong_hoadon", Storage="_phieuthuephong", ThisKey="maphieuthue", OtherKey="maphieuthue", IsForeignKey=true)]
		public phieuthuephong phieuthuephong
		{
			get
			{
				return this._phieuthuephong.Entity;
			}
			set
			{
				phieuthuephong previousValue = this._phieuthuephong.Entity;
				if (((previousValue != value) 
							|| (this._phieuthuephong.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._phieuthuephong.Entity = null;
						previousValue.hoadons.Remove(this);
					}
					this._phieuthuephong.Entity = value;
					if ((value != null))
					{
						value.hoadons.Add(this);
						this._maphieuthue = value.maphieuthue;
					}
					else
					{
						this._maphieuthue = default(string);
					}
					this.SendPropertyChanged("phieuthuephong");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.khachhang")]
	public partial class khachhang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _makhachhang;
		
		private string _tenkhachhang;
		
		private System.Nullable<bool> _gioitinh;
		
		private string _cmnd_passport;
		
		private string _diachi;
		
		private string _coquan;
		
		private string _sodienthoai;
		
		private string _email;
		
		private EntitySet<hoadon> _hoadons;
		
		private EntitySet<phieudatphong> _phieudatphongs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmakhachhangChanging(string value);
    partial void OnmakhachhangChanged();
    partial void OntenkhachhangChanging(string value);
    partial void OntenkhachhangChanged();
    partial void OngioitinhChanging(System.Nullable<bool> value);
    partial void OngioitinhChanged();
    partial void Oncmnd_passportChanging(string value);
    partial void Oncmnd_passportChanged();
    partial void OndiachiChanging(string value);
    partial void OndiachiChanged();
    partial void OncoquanChanging(string value);
    partial void OncoquanChanged();
    partial void OnsodienthoaiChanging(string value);
    partial void OnsodienthoaiChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    #endregion
		
		public khachhang()
		{
			this._hoadons = new EntitySet<hoadon>(new Action<hoadon>(this.attach_hoadons), new Action<hoadon>(this.detach_hoadons));
			this._phieudatphongs = new EntitySet<phieudatphong>(new Action<phieudatphong>(this.attach_phieudatphongs), new Action<phieudatphong>(this.detach_phieudatphongs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_makhachhang", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string makhachhang
		{
			get
			{
				return this._makhachhang;
			}
			set
			{
				if ((this._makhachhang != value))
				{
					this.OnmakhachhangChanging(value);
					this.SendPropertyChanging();
					this._makhachhang = value;
					this.SendPropertyChanged("makhachhang");
					this.OnmakhachhangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenkhachhang", DbType="NVarChar(50)")]
		public string tenkhachhang
		{
			get
			{
				return this._tenkhachhang;
			}
			set
			{
				if ((this._tenkhachhang != value))
				{
					this.OntenkhachhangChanging(value);
					this.SendPropertyChanging();
					this._tenkhachhang = value;
					this.SendPropertyChanged("tenkhachhang");
					this.OntenkhachhangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioitinh", DbType="Bit")]
		public System.Nullable<bool> gioitinh
		{
			get
			{
				return this._gioitinh;
			}
			set
			{
				if ((this._gioitinh != value))
				{
					this.OngioitinhChanging(value);
					this.SendPropertyChanging();
					this._gioitinh = value;
					this.SendPropertyChanged("gioitinh");
					this.OngioitinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cmnd_passport", DbType="VarChar(10)")]
		public string cmnd_passport
		{
			get
			{
				return this._cmnd_passport;
			}
			set
			{
				if ((this._cmnd_passport != value))
				{
					this.Oncmnd_passportChanging(value);
					this.SendPropertyChanging();
					this._cmnd_passport = value;
					this.SendPropertyChanged("cmnd_passport");
					this.Oncmnd_passportChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diachi", DbType="NVarChar(100)")]
		public string diachi
		{
			get
			{
				return this._diachi;
			}
			set
			{
				if ((this._diachi != value))
				{
					this.OndiachiChanging(value);
					this.SendPropertyChanging();
					this._diachi = value;
					this.SendPropertyChanged("diachi");
					this.OndiachiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_coquan", DbType="NVarChar(50)")]
		public string coquan
		{
			get
			{
				return this._coquan;
			}
			set
			{
				if ((this._coquan != value))
				{
					this.OncoquanChanging(value);
					this.SendPropertyChanging();
					this._coquan = value;
					this.SendPropertyChanged("coquan");
					this.OncoquanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sodienthoai", DbType="VarChar(11)")]
		public string sodienthoai
		{
			get
			{
				return this._sodienthoai;
			}
			set
			{
				if ((this._sodienthoai != value))
				{
					this.OnsodienthoaiChanging(value);
					this.SendPropertyChanging();
					this._sodienthoai = value;
					this.SendPropertyChanged("sodienthoai");
					this.OnsodienthoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(50)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="khachhang_hoadon", Storage="_hoadons", ThisKey="makhachhang", OtherKey="makhachhang")]
		public EntitySet<hoadon> hoadons
		{
			get
			{
				return this._hoadons;
			}
			set
			{
				this._hoadons.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="khachhang_phieudatphong", Storage="_phieudatphongs", ThisKey="makhachhang", OtherKey="makhachhang")]
		public EntitySet<phieudatphong> phieudatphongs
		{
			get
			{
				return this._phieudatphongs;
			}
			set
			{
				this._phieudatphongs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_hoadons(hoadon entity)
		{
			this.SendPropertyChanging();
			entity.khachhang = this;
		}
		
		private void detach_hoadons(hoadon entity)
		{
			this.SendPropertyChanging();
			entity.khachhang = null;
		}
		
		private void attach_phieudatphongs(phieudatphong entity)
		{
			this.SendPropertyChanging();
			entity.khachhang = this;
		}
		
		private void detach_phieudatphongs(phieudatphong entity)
		{
			this.SendPropertyChanging();
			entity.khachhang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.phong")]
	public partial class phong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maphong;
		
		private string _maloai;
		
		private System.Nullable<bool> _dadat;
		
		private System.Nullable<bool> _danhan;
		
		private EntitySet<chitietdatphong> _chitietdatphongs;
		
		private EntitySet<chitietthuephong> _chitietthuephongs;
		
		private EntitySet<trangthaiphong> _trangthaiphongs;
		
		private EntityRef<loaiphong> _loaiphong;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaphongChanging(string value);
    partial void OnmaphongChanged();
    partial void OnmaloaiChanging(string value);
    partial void OnmaloaiChanged();
    partial void OndadatChanging(System.Nullable<bool> value);
    partial void OndadatChanged();
    partial void OndanhanChanging(System.Nullable<bool> value);
    partial void OndanhanChanged();
    #endregion
		
		public phong()
		{
			this._chitietdatphongs = new EntitySet<chitietdatphong>(new Action<chitietdatphong>(this.attach_chitietdatphongs), new Action<chitietdatphong>(this.detach_chitietdatphongs));
			this._chitietthuephongs = new EntitySet<chitietthuephong>(new Action<chitietthuephong>(this.attach_chitietthuephongs), new Action<chitietthuephong>(this.detach_chitietthuephongs));
			this._trangthaiphongs = new EntitySet<trangthaiphong>(new Action<trangthaiphong>(this.attach_trangthaiphongs), new Action<trangthaiphong>(this.detach_trangthaiphongs));
			this._loaiphong = default(EntityRef<loaiphong>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maphong", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maphong
		{
			get
			{
				return this._maphong;
			}
			set
			{
				if ((this._maphong != value))
				{
					this.OnmaphongChanging(value);
					this.SendPropertyChanging();
					this._maphong = value;
					this.SendPropertyChanged("maphong");
					this.OnmaphongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maloai", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string maloai
		{
			get
			{
				return this._maloai;
			}
			set
			{
				if ((this._maloai != value))
				{
					if (this._loaiphong.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaloaiChanging(value);
					this.SendPropertyChanging();
					this._maloai = value;
					this.SendPropertyChanged("maloai");
					this.OnmaloaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dadat", DbType="Bit")]
		public System.Nullable<bool> dadat
		{
			get
			{
				return this._dadat;
			}
			set
			{
				if ((this._dadat != value))
				{
					this.OndadatChanging(value);
					this.SendPropertyChanging();
					this._dadat = value;
					this.SendPropertyChanged("dadat");
					this.OndadatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_danhan", DbType="Bit")]
		public System.Nullable<bool> danhan
		{
			get
			{
				return this._danhan;
			}
			set
			{
				if ((this._danhan != value))
				{
					this.OndanhanChanging(value);
					this.SendPropertyChanging();
					this._danhan = value;
					this.SendPropertyChanged("danhan");
					this.OndanhanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="phong_chitietdatphong", Storage="_chitietdatphongs", ThisKey="maphong", OtherKey="maphong")]
		public EntitySet<chitietdatphong> chitietdatphongs
		{
			get
			{
				return this._chitietdatphongs;
			}
			set
			{
				this._chitietdatphongs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="phong_chitietthuephong", Storage="_chitietthuephongs", ThisKey="maphong", OtherKey="maphong")]
		public EntitySet<chitietthuephong> chitietthuephongs
		{
			get
			{
				return this._chitietthuephongs;
			}
			set
			{
				this._chitietthuephongs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="phong_trangthaiphong", Storage="_trangthaiphongs", ThisKey="maphong", OtherKey="maphong")]
		public EntitySet<trangthaiphong> trangthaiphongs
		{
			get
			{
				return this._trangthaiphongs;
			}
			set
			{
				this._trangthaiphongs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="loaiphong_phong", Storage="_loaiphong", ThisKey="maloai", OtherKey="maloai", IsForeignKey=true)]
		public loaiphong loaiphong
		{
			get
			{
				return this._loaiphong.Entity;
			}
			set
			{
				loaiphong previousValue = this._loaiphong.Entity;
				if (((previousValue != value) 
							|| (this._loaiphong.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._loaiphong.Entity = null;
						previousValue.phongs.Remove(this);
					}
					this._loaiphong.Entity = value;
					if ((value != null))
					{
						value.phongs.Add(this);
						this._maloai = value.maloai;
					}
					else
					{
						this._maloai = default(string);
					}
					this.SendPropertyChanged("loaiphong");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_chitietdatphongs(chitietdatphong entity)
		{
			this.SendPropertyChanging();
			entity.phong = this;
		}
		
		private void detach_chitietdatphongs(chitietdatphong entity)
		{
			this.SendPropertyChanging();
			entity.phong = null;
		}
		
		private void attach_chitietthuephongs(chitietthuephong entity)
		{
			this.SendPropertyChanging();
			entity.phong = this;
		}
		
		private void detach_chitietthuephongs(chitietthuephong entity)
		{
			this.SendPropertyChanging();
			entity.phong = null;
		}
		
		private void attach_trangthaiphongs(trangthaiphong entity)
		{
			this.SendPropertyChanging();
			entity.phong = this;
		}
		
		private void detach_trangthaiphongs(trangthaiphong entity)
		{
			this.SendPropertyChanging();
			entity.phong = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.loaiphong")]
	public partial class loaiphong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maloai;
		
		private System.Nullable<decimal> _gia;
		
		private System.Nullable<int> _songuoi;
		
		private EntitySet<chitietvattu> _chitietvattus;
		
		private EntitySet<phong> _phongs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaloaiChanging(string value);
    partial void OnmaloaiChanged();
    partial void OngiaChanging(System.Nullable<decimal> value);
    partial void OngiaChanged();
    partial void OnsonguoiChanging(System.Nullable<int> value);
    partial void OnsonguoiChanged();
    #endregion
		
		public loaiphong()
		{
			this._chitietvattus = new EntitySet<chitietvattu>(new Action<chitietvattu>(this.attach_chitietvattus), new Action<chitietvattu>(this.detach_chitietvattus));
			this._phongs = new EntitySet<phong>(new Action<phong>(this.attach_phongs), new Action<phong>(this.detach_phongs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maloai", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maloai
		{
			get
			{
				return this._maloai;
			}
			set
			{
				if ((this._maloai != value))
				{
					this.OnmaloaiChanging(value);
					this.SendPropertyChanging();
					this._maloai = value;
					this.SendPropertyChanged("maloai");
					this.OnmaloaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gia", DbType="Money")]
		public System.Nullable<decimal> gia
		{
			get
			{
				return this._gia;
			}
			set
			{
				if ((this._gia != value))
				{
					this.OngiaChanging(value);
					this.SendPropertyChanging();
					this._gia = value;
					this.SendPropertyChanged("gia");
					this.OngiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_songuoi", DbType="Int")]
		public System.Nullable<int> songuoi
		{
			get
			{
				return this._songuoi;
			}
			set
			{
				if ((this._songuoi != value))
				{
					this.OnsonguoiChanging(value);
					this.SendPropertyChanging();
					this._songuoi = value;
					this.SendPropertyChanged("songuoi");
					this.OnsonguoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="loaiphong_chitietvattu", Storage="_chitietvattus", ThisKey="maloai", OtherKey="maloaiphong")]
		public EntitySet<chitietvattu> chitietvattus
		{
			get
			{
				return this._chitietvattus;
			}
			set
			{
				this._chitietvattus.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="loaiphong_phong", Storage="_phongs", ThisKey="maloai", OtherKey="maloai")]
		public EntitySet<phong> phongs
		{
			get
			{
				return this._phongs;
			}
			set
			{
				this._phongs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_chitietvattus(chitietvattu entity)
		{
			this.SendPropertyChanging();
			entity.loaiphong = this;
		}
		
		private void detach_chitietvattus(chitietvattu entity)
		{
			this.SendPropertyChanging();
			entity.loaiphong = null;
		}
		
		private void attach_phongs(phong entity)
		{
			this.SendPropertyChanging();
			entity.loaiphong = this;
		}
		
		private void detach_phongs(phong entity)
		{
			this.SendPropertyChanging();
			entity.loaiphong = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.nhanvien")]
	public partial class nhanvien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _manhanvien;
		
		private string _tennhanvien;
		
		private System.Nullable<System.DateTime> _ngaysinh;
		
		private System.Nullable<bool> _phai;
		
		private string _diachi;
		
		private string _phone;
		
		private string _chucvu;
		
		private EntitySet<hethong> _hethongs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmanhanvienChanging(string value);
    partial void OnmanhanvienChanged();
    partial void OntennhanvienChanging(string value);
    partial void OntennhanvienChanged();
    partial void OnngaysinhChanging(System.Nullable<System.DateTime> value);
    partial void OnngaysinhChanged();
    partial void OnphaiChanging(System.Nullable<bool> value);
    partial void OnphaiChanged();
    partial void OndiachiChanging(string value);
    partial void OndiachiChanged();
    partial void OnphoneChanging(string value);
    partial void OnphoneChanged();
    partial void OnchucvuChanging(string value);
    partial void OnchucvuChanged();
    #endregion
		
		public nhanvien()
		{
			this._hethongs = new EntitySet<hethong>(new Action<hethong>(this.attach_hethongs), new Action<hethong>(this.detach_hethongs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_manhanvien", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string manhanvien
		{
			get
			{
				return this._manhanvien;
			}
			set
			{
				if ((this._manhanvien != value))
				{
					this.OnmanhanvienChanging(value);
					this.SendPropertyChanging();
					this._manhanvien = value;
					this.SendPropertyChanged("manhanvien");
					this.OnmanhanvienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tennhanvien", DbType="NVarChar(50)")]
		public string tennhanvien
		{
			get
			{
				return this._tennhanvien;
			}
			set
			{
				if ((this._tennhanvien != value))
				{
					this.OntennhanvienChanging(value);
					this.SendPropertyChanging();
					this._tennhanvien = value;
					this.SendPropertyChanged("tennhanvien");
					this.OntennhanvienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaysinh", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngaysinh
		{
			get
			{
				return this._ngaysinh;
			}
			set
			{
				if ((this._ngaysinh != value))
				{
					this.OnngaysinhChanging(value);
					this.SendPropertyChanging();
					this._ngaysinh = value;
					this.SendPropertyChanged("ngaysinh");
					this.OnngaysinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phai", DbType="Bit")]
		public System.Nullable<bool> phai
		{
			get
			{
				return this._phai;
			}
			set
			{
				if ((this._phai != value))
				{
					this.OnphaiChanging(value);
					this.SendPropertyChanging();
					this._phai = value;
					this.SendPropertyChanged("phai");
					this.OnphaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diachi", DbType="NVarChar(100)")]
		public string diachi
		{
			get
			{
				return this._diachi;
			}
			set
			{
				if ((this._diachi != value))
				{
					this.OndiachiChanging(value);
					this.SendPropertyChanging();
					this._diachi = value;
					this.SendPropertyChanged("diachi");
					this.OndiachiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone", DbType="VarChar(11)")]
		public string phone
		{
			get
			{
				return this._phone;
			}
			set
			{
				if ((this._phone != value))
				{
					this.OnphoneChanging(value);
					this.SendPropertyChanging();
					this._phone = value;
					this.SendPropertyChanged("phone");
					this.OnphoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_chucvu", DbType="NVarChar(50)")]
		public string chucvu
		{
			get
			{
				return this._chucvu;
			}
			set
			{
				if ((this._chucvu != value))
				{
					this.OnchucvuChanging(value);
					this.SendPropertyChanging();
					this._chucvu = value;
					this.SendPropertyChanged("chucvu");
					this.OnchucvuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="nhanvien_hethong", Storage="_hethongs", ThisKey="manhanvien", OtherKey="manhanvien")]
		public EntitySet<hethong> hethongs
		{
			get
			{
				return this._hethongs;
			}
			set
			{
				this._hethongs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_hethongs(hethong entity)
		{
			this.SendPropertyChanging();
			entity.nhanvien = this;
		}
		
		private void detach_hethongs(hethong entity)
		{
			this.SendPropertyChanging();
			entity.nhanvien = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.phieudatphong")]
	public partial class phieudatphong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maphieudat;
		
		private string _makhachhang;
		
		private System.Nullable<System.DateTime> _ngayden;
		
		private System.Nullable<System.DateTime> _ngaydi;
		
		private System.Nullable<decimal> _sotiendatcoc;
		
		private string _username;
		
		private string _tinhtrang;
		
		private System.Nullable<int> _songuoi;
		
		private EntitySet<chitietdatphong> _chitietdatphongs;
		
		private EntitySet<phieuthuephong> _phieuthuephongs;
		
		private EntityRef<khachhang> _khachhang;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaphieudatChanging(string value);
    partial void OnmaphieudatChanged();
    partial void OnmakhachhangChanging(string value);
    partial void OnmakhachhangChanged();
    partial void OnngaydenChanging(System.Nullable<System.DateTime> value);
    partial void OnngaydenChanged();
    partial void OnngaydiChanging(System.Nullable<System.DateTime> value);
    partial void OnngaydiChanged();
    partial void OnsotiendatcocChanging(System.Nullable<decimal> value);
    partial void OnsotiendatcocChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OntinhtrangChanging(string value);
    partial void OntinhtrangChanged();
    partial void OnsonguoiChanging(System.Nullable<int> value);
    partial void OnsonguoiChanged();
    #endregion
		
		public phieudatphong()
		{
			this._chitietdatphongs = new EntitySet<chitietdatphong>(new Action<chitietdatphong>(this.attach_chitietdatphongs), new Action<chitietdatphong>(this.detach_chitietdatphongs));
			this._phieuthuephongs = new EntitySet<phieuthuephong>(new Action<phieuthuephong>(this.attach_phieuthuephongs), new Action<phieuthuephong>(this.detach_phieuthuephongs));
			this._khachhang = default(EntityRef<khachhang>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maphieudat", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maphieudat
		{
			get
			{
				return this._maphieudat;
			}
			set
			{
				if ((this._maphieudat != value))
				{
					this.OnmaphieudatChanging(value);
					this.SendPropertyChanging();
					this._maphieudat = value;
					this.SendPropertyChanged("maphieudat");
					this.OnmaphieudatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_makhachhang", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string makhachhang
		{
			get
			{
				return this._makhachhang;
			}
			set
			{
				if ((this._makhachhang != value))
				{
					if (this._khachhang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmakhachhangChanging(value);
					this.SendPropertyChanging();
					this._makhachhang = value;
					this.SendPropertyChanged("makhachhang");
					this.OnmakhachhangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayden", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngayden
		{
			get
			{
				return this._ngayden;
			}
			set
			{
				if ((this._ngayden != value))
				{
					this.OnngaydenChanging(value);
					this.SendPropertyChanging();
					this._ngayden = value;
					this.SendPropertyChanged("ngayden");
					this.OnngaydenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaydi", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngaydi
		{
			get
			{
				return this._ngaydi;
			}
			set
			{
				if ((this._ngaydi != value))
				{
					this.OnngaydiChanging(value);
					this.SendPropertyChanging();
					this._ngaydi = value;
					this.SendPropertyChanged("ngaydi");
					this.OnngaydiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sotiendatcoc", DbType="Money")]
		public System.Nullable<decimal> sotiendatcoc
		{
			get
			{
				return this._sotiendatcoc;
			}
			set
			{
				if ((this._sotiendatcoc != value))
				{
					this.OnsotiendatcocChanging(value);
					this.SendPropertyChanging();
					this._sotiendatcoc = value;
					this.SendPropertyChanged("sotiendatcoc");
					this.OnsotiendatcocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="VarChar(10)")]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tinhtrang", DbType="VarChar(10)")]
		public string tinhtrang
		{
			get
			{
				return this._tinhtrang;
			}
			set
			{
				if ((this._tinhtrang != value))
				{
					this.OntinhtrangChanging(value);
					this.SendPropertyChanging();
					this._tinhtrang = value;
					this.SendPropertyChanged("tinhtrang");
					this.OntinhtrangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_songuoi", DbType="Int")]
		public System.Nullable<int> songuoi
		{
			get
			{
				return this._songuoi;
			}
			set
			{
				if ((this._songuoi != value))
				{
					this.OnsonguoiChanging(value);
					this.SendPropertyChanging();
					this._songuoi = value;
					this.SendPropertyChanged("songuoi");
					this.OnsonguoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="phieudatphong_chitietdatphong", Storage="_chitietdatphongs", ThisKey="maphieudat", OtherKey="maphieudat")]
		public EntitySet<chitietdatphong> chitietdatphongs
		{
			get
			{
				return this._chitietdatphongs;
			}
			set
			{
				this._chitietdatphongs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="phieudatphong_phieuthuephong", Storage="_phieuthuephongs", ThisKey="maphieudat", OtherKey="maphieudat")]
		public EntitySet<phieuthuephong> phieuthuephongs
		{
			get
			{
				return this._phieuthuephongs;
			}
			set
			{
				this._phieuthuephongs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="khachhang_phieudatphong", Storage="_khachhang", ThisKey="makhachhang", OtherKey="makhachhang", IsForeignKey=true)]
		public khachhang khachhang
		{
			get
			{
				return this._khachhang.Entity;
			}
			set
			{
				khachhang previousValue = this._khachhang.Entity;
				if (((previousValue != value) 
							|| (this._khachhang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._khachhang.Entity = null;
						previousValue.phieudatphongs.Remove(this);
					}
					this._khachhang.Entity = value;
					if ((value != null))
					{
						value.phieudatphongs.Add(this);
						this._makhachhang = value.makhachhang;
					}
					else
					{
						this._makhachhang = default(string);
					}
					this.SendPropertyChanged("khachhang");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_chitietdatphongs(chitietdatphong entity)
		{
			this.SendPropertyChanging();
			entity.phieudatphong = this;
		}
		
		private void detach_chitietdatphongs(chitietdatphong entity)
		{
			this.SendPropertyChanging();
			entity.phieudatphong = null;
		}
		
		private void attach_phieuthuephongs(phieuthuephong entity)
		{
			this.SendPropertyChanging();
			entity.phieudatphong = this;
		}
		
		private void detach_phieuthuephongs(phieuthuephong entity)
		{
			this.SendPropertyChanging();
			entity.phieudatphong = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.phieuthuephong")]
	public partial class phieuthuephong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maphieuthue;
		
		private string _maphieudat;
		
		private string _username;
		
		private EntitySet<chitietthuephong> _chitietthuephongs;
		
		private EntitySet<hoadon> _hoadons;
		
		private EntityRef<hethong> _hethong;
		
		private EntityRef<phieudatphong> _phieudatphong;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaphieuthueChanging(string value);
    partial void OnmaphieuthueChanged();
    partial void OnmaphieudatChanging(string value);
    partial void OnmaphieudatChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    #endregion
		
		public phieuthuephong()
		{
			this._chitietthuephongs = new EntitySet<chitietthuephong>(new Action<chitietthuephong>(this.attach_chitietthuephongs), new Action<chitietthuephong>(this.detach_chitietthuephongs));
			this._hoadons = new EntitySet<hoadon>(new Action<hoadon>(this.attach_hoadons), new Action<hoadon>(this.detach_hoadons));
			this._hethong = default(EntityRef<hethong>);
			this._phieudatphong = default(EntityRef<phieudatphong>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maphieuthue", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maphieuthue
		{
			get
			{
				return this._maphieuthue;
			}
			set
			{
				if ((this._maphieuthue != value))
				{
					this.OnmaphieuthueChanging(value);
					this.SendPropertyChanging();
					this._maphieuthue = value;
					this.SendPropertyChanged("maphieuthue");
					this.OnmaphieuthueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maphieudat", DbType="VarChar(10)")]
		public string maphieudat
		{
			get
			{
				return this._maphieudat;
			}
			set
			{
				if ((this._maphieudat != value))
				{
					if (this._phieudatphong.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaphieudatChanging(value);
					this.SendPropertyChanging();
					this._maphieudat = value;
					this.SendPropertyChanged("maphieudat");
					this.OnmaphieudatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="VarChar(10)")]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					if (this._hethong.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="phieuthuephong_chitietthuephong", Storage="_chitietthuephongs", ThisKey="maphieuthue", OtherKey="maphieuthue")]
		public EntitySet<chitietthuephong> chitietthuephongs
		{
			get
			{
				return this._chitietthuephongs;
			}
			set
			{
				this._chitietthuephongs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="phieuthuephong_hoadon", Storage="_hoadons", ThisKey="maphieuthue", OtherKey="maphieuthue")]
		public EntitySet<hoadon> hoadons
		{
			get
			{
				return this._hoadons;
			}
			set
			{
				this._hoadons.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="hethong_phieuthuephong", Storage="_hethong", ThisKey="username", OtherKey="username", IsForeignKey=true)]
		public hethong hethong
		{
			get
			{
				return this._hethong.Entity;
			}
			set
			{
				hethong previousValue = this._hethong.Entity;
				if (((previousValue != value) 
							|| (this._hethong.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._hethong.Entity = null;
						previousValue.phieuthuephongs.Remove(this);
					}
					this._hethong.Entity = value;
					if ((value != null))
					{
						value.phieuthuephongs.Add(this);
						this._username = value.username;
					}
					else
					{
						this._username = default(string);
					}
					this.SendPropertyChanged("hethong");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="phieudatphong_phieuthuephong", Storage="_phieudatphong", ThisKey="maphieudat", OtherKey="maphieudat", IsForeignKey=true)]
		public phieudatphong phieudatphong
		{
			get
			{
				return this._phieudatphong.Entity;
			}
			set
			{
				phieudatphong previousValue = this._phieudatphong.Entity;
				if (((previousValue != value) 
							|| (this._phieudatphong.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._phieudatphong.Entity = null;
						previousValue.phieuthuephongs.Remove(this);
					}
					this._phieudatphong.Entity = value;
					if ((value != null))
					{
						value.phieuthuephongs.Add(this);
						this._maphieudat = value.maphieudat;
					}
					else
					{
						this._maphieudat = default(string);
					}
					this.SendPropertyChanged("phieudatphong");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_chitietthuephongs(chitietthuephong entity)
		{
			this.SendPropertyChanging();
			entity.phieuthuephong = this;
		}
		
		private void detach_chitietthuephongs(chitietthuephong entity)
		{
			this.SendPropertyChanging();
			entity.phieuthuephong = null;
		}
		
		private void attach_hoadons(hoadon entity)
		{
			this.SendPropertyChanging();
			entity.phieuthuephong = this;
		}
		
		private void detach_hoadons(hoadon entity)
		{
			this.SendPropertyChanging();
			entity.phieuthuephong = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.trangthaiphong")]
	public partial class trangthaiphong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maphong;
		
		private string _trangthai;
		
		private EntityRef<phong> _phong;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaphongChanging(string value);
    partial void OnmaphongChanged();
    partial void OntrangthaiChanging(string value);
    partial void OntrangthaiChanged();
    #endregion
		
		public trangthaiphong()
		{
			this._phong = default(EntityRef<phong>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maphong", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maphong
		{
			get
			{
				return this._maphong;
			}
			set
			{
				if ((this._maphong != value))
				{
					if (this._phong.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaphongChanging(value);
					this.SendPropertyChanging();
					this._maphong = value;
					this.SendPropertyChanged("maphong");
					this.OnmaphongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trangthai", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string trangthai
		{
			get
			{
				return this._trangthai;
			}
			set
			{
				if ((this._trangthai != value))
				{
					this.OntrangthaiChanging(value);
					this.SendPropertyChanging();
					this._trangthai = value;
					this.SendPropertyChanged("trangthai");
					this.OntrangthaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="phong_trangthaiphong", Storage="_phong", ThisKey="maphong", OtherKey="maphong", IsForeignKey=true)]
		public phong phong
		{
			get
			{
				return this._phong.Entity;
			}
			set
			{
				phong previousValue = this._phong.Entity;
				if (((previousValue != value) 
							|| (this._phong.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._phong.Entity = null;
						previousValue.trangthaiphongs.Remove(this);
					}
					this._phong.Entity = value;
					if ((value != null))
					{
						value.trangthaiphongs.Add(this);
						this._maphong = value.maphong;
					}
					else
					{
						this._maphong = default(string);
					}
					this.SendPropertyChanged("phong");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vattu")]
	public partial class vattu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _mavattu;
		
		private string _tenvattu;
		
		private EntitySet<chitietvattu> _chitietvattus;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmavattuChanging(string value);
    partial void OnmavattuChanged();
    partial void OntenvattuChanging(string value);
    partial void OntenvattuChanged();
    #endregion
		
		public vattu()
		{
			this._chitietvattus = new EntitySet<chitietvattu>(new Action<chitietvattu>(this.attach_chitietvattus), new Action<chitietvattu>(this.detach_chitietvattus));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mavattu", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string mavattu
		{
			get
			{
				return this._mavattu;
			}
			set
			{
				if ((this._mavattu != value))
				{
					this.OnmavattuChanging(value);
					this.SendPropertyChanging();
					this._mavattu = value;
					this.SendPropertyChanged("mavattu");
					this.OnmavattuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenvattu", DbType="NVarChar(50)")]
		public string tenvattu
		{
			get
			{
				return this._tenvattu;
			}
			set
			{
				if ((this._tenvattu != value))
				{
					this.OntenvattuChanging(value);
					this.SendPropertyChanging();
					this._tenvattu = value;
					this.SendPropertyChanged("tenvattu");
					this.OntenvattuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="vattu_chitietvattu", Storage="_chitietvattus", ThisKey="mavattu", OtherKey="mavattu")]
		public EntitySet<chitietvattu> chitietvattus
		{
			get
			{
				return this._chitietvattus;
			}
			set
			{
				this._chitietvattus.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_chitietvattus(chitietvattu entity)
		{
			this.SendPropertyChanging();
			entity.vattu = this;
		}
		
		private void detach_chitietvattus(chitietvattu entity)
		{
			this.SendPropertyChanging();
			entity.vattu = null;
		}
	}
	
	public partial class InhoadonDichVuResult
	{
		
		private string _maphieuthue;
		
		private string _tendichvu;
		
		private System.Nullable<decimal> _gia;
		
		private string _donvitinh;
		
		private System.Nullable<int> _soluong;
		
		private string _maphong;
		
		private string _mahoadon;
		
		private System.DateTime _ngay;
		
		public InhoadonDichVuResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maphieuthue", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string maphieuthue
		{
			get
			{
				return this._maphieuthue;
			}
			set
			{
				if ((this._maphieuthue != value))
				{
					this._maphieuthue = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tendichvu", DbType="NVarChar(50)")]
		public string tendichvu
		{
			get
			{
				return this._tendichvu;
			}
			set
			{
				if ((this._tendichvu != value))
				{
					this._tendichvu = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gia", DbType="Money")]
		public System.Nullable<decimal> gia
		{
			get
			{
				return this._gia;
			}
			set
			{
				if ((this._gia != value))
				{
					this._gia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_donvitinh", DbType="NChar(10)")]
		public string donvitinh
		{
			get
			{
				return this._donvitinh;
			}
			set
			{
				if ((this._donvitinh != value))
				{
					this._donvitinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soluong", DbType="Int")]
		public System.Nullable<int> soluong
		{
			get
			{
				return this._soluong;
			}
			set
			{
				if ((this._soluong != value))
				{
					this._soluong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maphong", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string maphong
		{
			get
			{
				return this._maphong;
			}
			set
			{
				if ((this._maphong != value))
				{
					this._maphong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mahoadon", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string mahoadon
		{
			get
			{
				return this._mahoadon;
			}
			set
			{
				if ((this._mahoadon != value))
				{
					this._mahoadon = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay", DbType="DateTime NOT NULL")]
		public System.DateTime ngay
		{
			get
			{
				return this._ngay;
			}
			set
			{
				if ((this._ngay != value))
				{
					this._ngay = value;
				}
			}
		}
	}
	
	public partial class InhoadonPhongResult
	{
		
		private string _mahoadon;
		
		private string _tenkhachhang;
		
		private System.Nullable<int> _ngayo;
		
		private string _cmnd_passport;
		
		private string _diachi;
		
		private string _coquan;
		
		private string _sodienthoai;
		
		private string _email;
		
		private System.Nullable<System.DateTime> _ngayden;
		
		private System.Nullable<System.DateTime> _ngaydi;
		
		private System.Nullable<decimal> _sotiendatcoc;
		
		private System.Nullable<decimal> _gia;
		
		private string _maphong;
		
		private string _tennhanvien;
		
		private System.Nullable<decimal> _tongtien;
		
		public InhoadonPhongResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mahoadon", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string mahoadon
		{
			get
			{
				return this._mahoadon;
			}
			set
			{
				if ((this._mahoadon != value))
				{
					this._mahoadon = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenkhachhang", DbType="NVarChar(50)")]
		public string tenkhachhang
		{
			get
			{
				return this._tenkhachhang;
			}
			set
			{
				if ((this._tenkhachhang != value))
				{
					this._tenkhachhang = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayo", DbType="Int")]
		public System.Nullable<int> ngayo
		{
			get
			{
				return this._ngayo;
			}
			set
			{
				if ((this._ngayo != value))
				{
					this._ngayo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cmnd_passport", DbType="VarChar(10)")]
		public string cmnd_passport
		{
			get
			{
				return this._cmnd_passport;
			}
			set
			{
				if ((this._cmnd_passport != value))
				{
					this._cmnd_passport = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diachi", DbType="NVarChar(100)")]
		public string diachi
		{
			get
			{
				return this._diachi;
			}
			set
			{
				if ((this._diachi != value))
				{
					this._diachi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_coquan", DbType="NVarChar(50)")]
		public string coquan
		{
			get
			{
				return this._coquan;
			}
			set
			{
				if ((this._coquan != value))
				{
					this._coquan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sodienthoai", DbType="VarChar(11)")]
		public string sodienthoai
		{
			get
			{
				return this._sodienthoai;
			}
			set
			{
				if ((this._sodienthoai != value))
				{
					this._sodienthoai = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(50)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this._email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayden", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngayden
		{
			get
			{
				return this._ngayden;
			}
			set
			{
				if ((this._ngayden != value))
				{
					this._ngayden = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaydi", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngaydi
		{
			get
			{
				return this._ngaydi;
			}
			set
			{
				if ((this._ngaydi != value))
				{
					this._ngaydi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sotiendatcoc", DbType="Money")]
		public System.Nullable<decimal> sotiendatcoc
		{
			get
			{
				return this._sotiendatcoc;
			}
			set
			{
				if ((this._sotiendatcoc != value))
				{
					this._sotiendatcoc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gia", DbType="Money")]
		public System.Nullable<decimal> gia
		{
			get
			{
				return this._gia;
			}
			set
			{
				if ((this._gia != value))
				{
					this._gia = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maphong", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string maphong
		{
			get
			{
				return this._maphong;
			}
			set
			{
				if ((this._maphong != value))
				{
					this._maphong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tennhanvien", DbType="NVarChar(50)")]
		public string tennhanvien
		{
			get
			{
				return this._tennhanvien;
			}
			set
			{
				if ((this._tennhanvien != value))
				{
					this._tennhanvien = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tongtien", DbType="Money")]
		public System.Nullable<decimal> tongtien
		{
			get
			{
				return this._tongtien;
			}
			set
			{
				if ((this._tongtien != value))
				{
					this._tongtien = value;
				}
			}
		}
	}
	
	public partial class kiemtraphongResult
	{
		
		private string _maphieudat;
		
		private string _maphong;
		
		private System.Nullable<System.DateTime> _ngayden;
		
		private System.Nullable<System.DateTime> _ngaydi;
		
		private string _tinhtrang;
		
		public kiemtraphongResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maphieudat", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string maphieudat
		{
			get
			{
				return this._maphieudat;
			}
			set
			{
				if ((this._maphieudat != value))
				{
					this._maphieudat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maphong", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string maphong
		{
			get
			{
				return this._maphong;
			}
			set
			{
				if ((this._maphong != value))
				{
					this._maphong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayden", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngayden
		{
			get
			{
				return this._ngayden;
			}
			set
			{
				if ((this._ngayden != value))
				{
					this._ngayden = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaydi", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngaydi
		{
			get
			{
				return this._ngaydi;
			}
			set
			{
				if ((this._ngaydi != value))
				{
					this._ngaydi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tinhtrang", DbType="VarChar(10)")]
		public string tinhtrang
		{
			get
			{
				return this._tinhtrang;
			}
			set
			{
				if ((this._tinhtrang != value))
				{
					this._tinhtrang = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
